#spring profile for docker
spring:  profiles: container
#eureka configuration
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2        #ribbon configuration load balancing
ribbon:  eureka:    enabled: true